os: linux
sudo: required
language: generic

install:
  - sudo apt-get update -qq
# - sudo apt-get install sdcc
  - bash ./.build-sdcc.sh
  - sdcc --version

before_script:
  - wget https://github.com/stateos/StateOS/archive/master.zip
  - unzip -q master.zip
  - mv StateOS-master/StateOS/* StateOS/
  - rm -r StateOS-master

script: make all SDCC= -f makefile.sdcc
