sudo: required

language: c

os: linux

dist: trusty

compiler: sdcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install sdcc

install:
  - wget https://github.com/stateos/StateOS/archive/master.zip -O StateOS-master.zip
# - unzip -q -d . StateOS-master.zip StateOS-master/StateOS/kernel/*
# - mv -T StateOS-master/StateOS/kernel/ StateOS/kernel/

before_script: sdcc --version

script: make all SDCC= -f makefile.sdcc

group: stable
